### ISSUE TITLE
Ta bort datum för ServiceEncounter i vis-funktionen

### ISSUE THREAD

**Issue by eribul** [cancercentrum/rccmisc#30]
Tils vidare exporterar vi inte dessa uppgifter då de är frivilliga och de nästan ändå är samma som de intervallvärden som visas. Å andra sidan är det väl bara just dessa värden vi faktiskt exporterar från R!? Så kanske var det aldrig tanken att värderna i denssa variabler skulle göras om till perioddatum utan tanken var kanske att dessa datum alltid ska utgöra `min` och `max`-datum inom perioden?

**Comment by eribul** [comment]
@Cstaf Blev nu lite osäker på denna. Se ovan!

**Comment by Cstaf** [comment]
Skicka datumen men skicka dem tomma, tills vidare. Vi skickade denna som blank vid första test.
